"""Generate neutral *narrative* stories (not Q&A dialogues) to replace the
original neutral baseline. Uses the same prompt structure as concept stories
but with explicit flat-affect instructions.

Model: Qwen3.5-Base NF4 (BASE_MODEL_ID). The original concept stories were
generated by a different model (Qwen3.6-Instruct, since deleted) — model-
mismatch is a smaller confound than narrative-vs-Q&A.

Output: runs/emotions_qwen35_neutral_narr/stories/_neutral-<tidx>-<sidx>.txt
        runs/emotions_qwen35_neutral_narr/stories/_raw/_neutral-<tidx>.txt

Usage:
    python scripts/generate_neutral_narratives.py                  # all 24 topics
    python scripts/generate_neutral_narratives.py --topic-ids 0    # dry run on 1 topic
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tqdm.auto import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import config                                                      # noqa: E402
from cv_utils import load_model                                    # noqa: E402
from extract_concepts import ensure_multi_story, read_lines        # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prompt-file",
                    default="inputs/emotions/neutral_narrative_prompt.txt", type=Path)
    ap.add_argument("--topics-file",
                    default="inputs/emotions/concept_topics.txt", type=Path)
    ap.add_argument("--out-dir",
                    default="runs/emotions_qwen35_neutral_narr", type=Path)
    ap.add_argument("--n-stories", type=int, default=12)
    ap.add_argument("--max-new-tokens", type=int, default=4000)
    ap.add_argument("--temperature", type=float, default=config.GEN_TEMPERATURE)
    ap.add_argument("--topic-ids", default=None,
                    help="Comma-separated topic indices, e.g. '0,5'. Default = all.")
    ap.add_argument("--model-id", default=config.BASE_MODEL_ID)
    args = ap.parse_args()

    topics = read_lines(args.topics_file)
    prompt_template = args.prompt_file.read_text()

    if args.topic_ids:
        ids = [int(x) for x in args.topic_ids.split(",")]
        topics = [(i, topics[i]) for i in ids]
    else:
        topics = list(enumerate(topics))

    stories_dir = args.out_dir / "stories"
    stories_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output dir: {stories_dir}")
    print(f"Generating {args.n_stories} stories × {len(topics)} topics = "
          f"{args.n_stories * len(topics)} stories total")
    print(f"Loading model: {args.model_id}")
    model = load_model(model_id=args.model_id)

    pbar = tqdm(topics, desc="gen neutral narrative", unit="topic")
    for tidx, topic in pbar:
        prefix = f"_neutral-{tidx}"
        pbar.set_postfix_str(prefix)
        prompt = prompt_template.format(topic=topic, n_stories=args.n_stories)
        ensure_multi_story(model, stories_dir, prefix, args.n_stories,
                           prompt, args.max_new_tokens, args.temperature)


if __name__ == "__main__":
    main()
